// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.perception;

option go_package = "intrinsic/perception/proto/distortion_params_go_proto";

// Distortion model and parameters.
message DistortionParams {
  // First radial distortion coefficient.
  double k1 = 1;

  // Second radial distortion coefficient.
  double k2 = 2;

  // First tangetial distortion coefficient.
  double p1 = 4;

  // Second tangetial distortion coefficient.
  double p2 = 5;

  // Third radial distortion coefficient.
  optional double k3 = 3;

  // Fourth radial distortion coefficient.
  optional double k4 = 6;

  // Fifth radial distortion coefficient.
  optional double k5 = 7;

  // Sixth radial distortion coefficient.
  optional double k6 = 8;

  // First thin prism distortion coefficient.
  optional double s1 = 9;

  // Second thin prism distortion coefficient.
  optional double s2 = 10;

  // Third thin prism distortion coefficient.
  optional double s3 = 11;

  // Fourth thin prism distortion coefficient.
  optional double s4 = 12;

  // First tilt distortion coefficient.
  optional double tx = 13;

  // Second tilt distortion coefficient.
  optional double ty = 14;
}
