// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.perception;

import "intrinsic/perception/proto/dimensions.proto";

option go_package = "intrinsic/perception/proto/intrinsic_params_go_proto";

// Internal camera parameters such as focal length and principal point.
message IntrinsicParams {
  // Focal length in horizontal direction. Required.
  // The focal length is specified in pixels.
  double focal_length_x = 1;

  // Focal length in vertical direction. Required.
  // The focal length is specified in pixels.
  double focal_length_y = 2;

  // Horizontal location of the principal point in the image plane. Required.
  // The principal point is specified in pixels.
  double principal_point_x = 3;

  // Vertical location of the principal point in the image plane. Required.
  // The principal point is specified in pixels.
  double principal_point_y = 4;

  // The dimensions of the image plane.
  Dimensions dimensions = 5;
}
