# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

metadata {
  id {
    package: "ai.intrinsic"
    name: "inference_service"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "This service provides an inference server that can load models and provides an open inference protocol API."
  }
  display_name: "ML Inference Service"
}
service_def {
  config_message_full_name: "intrinsic_proto.ml.inference_service.v1.InferenceServiceConfig"
  service_proto_prefixes: "/inference.GRPCInferenceService/"
  service_state_config {
    service_versions: INTRINSIC_PROTO_SERVICES_V1_SERVICE_STATE
  }
  real_spec {
    image {
      archive_filename: "inference_service_image.tar"
      settings {
        volume_mounts {
          name: "models-volume"
          mount_path: "/models"
        }
        volume_mounts {
          name: "inference-shm"
          mount_path: "/dev/shm"
        }
      }
    }
    extra_images {
      archive_filename: "onnxruntime_server_image.tar"
      settings {
        volume_mounts {
          name: "models-volume"
          mount_path: "/models"
        }
        volume_mounts {
          name: "inference-shm"
          mount_path: "/dev/shm"
        }
        args: [
          "--model-repository=/models",
          "--allow-client-shm=true",
          "--allow-http=false",
          "--allow-grpc=true",
          "--grpc-address=unix:///dev/shm/triton.sock",
          "--grpc-port=0",
          "--metrics-port=8002",
          "--model-control-mode=explicit",
          "--trace-config=mode=opentelemetry",
          "--trace-config=opentelemetry,url=http://oc-agent.app-intrinsic-base.svc.cluster.local:4318/v1/traces",
          "--trace-config=opentelemetry,resource=service.name=inference_service.onnxruntime",
          "--trace-config=rate=0",  # Only create trace when request has otel context attached.
          "--trace-config=level=TIMESTAMPS"
        ]
      }
    }
    settings {
      volumes {
        name: "models-volume"
        empty_dir {}
      }
      volumes {
        name: "inference-shm"
        empty_dir {
          medium: EMPTY_DIR_MEDIUM_MEMORY
        }
      }
    }
  }
  sim_spec {
    image {
      archive_filename: "inference_service_image.tar"
      settings {
        volume_mounts {
          name: "models-volume"
          mount_path: "/models"
        }
        volume_mounts {
          name: "inference-shm"
          mount_path: "/dev/shm"
        }
      }
    }
    extra_images {
      archive_filename: "onnxruntime_server_image.tar"
      settings {
        volume_mounts {
          name: "models-volume"
          mount_path: "/models"
        }
        volume_mounts {
          name: "inference-shm"
          mount_path: "/dev/shm"
        }
        args: [
          "--model-repository=/models",
          "--allow-client-shm=true",
          "--allow-http=false",
          "--allow-grpc=true",
          "--grpc-address=unix:///dev/shm/triton.sock",
          "--grpc-port=0",
          "--metrics-port=8002",
          "--model-control-mode=explicit",
          "--trace-config=mode=opentelemetry",
          "--trace-config=opentelemetry,url=http://oc-agent.app-intrinsic-base.svc.cluster.local:4318/v1/traces",
          "--trace-config=opentelemetry,resource=service.name=inference_service.onnxruntime",
          "--trace-config=rate=0",  # Only create trace when request has otel context attached.
          "--trace-config=level=TIMESTAMPS"
        ]
      }
    }
    settings {
      volumes {
        name: "models-volume"
        empty_dir {}
      }
      volumes {
        name: "inference-shm"
        empty_dir {
          medium: EMPTY_DIR_MEDIUM_MEMORY
        }
      }
    }
  }
}
